name: Run Feature Script Hourly

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  feature-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t aqi_prediction:latest .

      - name: Run Feature Script in Docker
        run: docker run -p 8000:8000 -p 8501:8501 aqi_prediction:latest bash -c "python api_data_fetch.py && cd feature_repo && feast apply && python aqi_workflow.py"

